var data = [
    "Keyword : Komputer - Nama Jurnal : Jurnal Ilmu Komputer dan Bisnis (JIKB) - Instansi : STMIK Dharmapala Riau - Website : https://stmikdharmapalariau.ac.id/ojs/index.php/jikb - Waktu Terbit : Mei, November - Biaya : 200,000 - Sinta : 1 - Tahun : 2021",
    "Keyword : adaptive learning - Nama Jurnal : Pengembangan adaptive mobile learning pada mata pelajaran biologi SMA sebagai upaya mendukung proses blended learning - Instansi : Universitas Negeri Yogyakarta - Website : https://journal.uny.ac.id/index.php/jitp/article/view/9723- Waktu Terbit : April - Biaya : -  - Sinta : 1 - Tahun : 2017",
    "Keyword : Sainstech - Nama Jurnal : Sainstech: Jurnal Penelitian dan Pengkajian Sains dan Teknologi - Instansi : Institut Sains dan Teknologi Nasional - Website : https://ejournal.istn.ac.id/index.php/sainstech - Waktu Terbit : Juli - Biaya : - - Sinta : 5 - Tahun : 2019",
    "Keyword : Informatika dan Teknologi - Nama Jurnal : NTEK : Informatika dan Teknologi Informasi - Instansi : Program Studi Teknologi Informasi Universitas Muhammadiyah Purworejo - Website : http://jurnal.umpwr.ac.id/index.php/intek/ - Waktu Terbit : Mei dan november - Biaya : 250,000 - Sinta : 6 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Informasi - Instansi : LPPM Universitas Respati Indonesia - Website : http://ejournal.urindo.ac.id/index.php/TI - Waktu Terbit : juni, Desember - Biaya : 400000 - Sinta : 6 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : Jurnal LENTERA : Kajian Keagamaan, Keilmuan dan Teknologi - Instansi : STAI MIFTAHUL ULA NGANJUK - Website : http://ejournal.staimnglawak.ac.id/index.php/lentera/ - Waktu Terbit : maret, september - Biaya : - Sinta : 6 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi TECHNOSCIENTIA - Instansi : Institut Sains & Teknologi AKPRIND Yogyakarta - Website : https://ejournal.akprind.ac.id/index.php/technoscientia/about - Waktu Terbit : - Februari, Agustus - Biaya : 250 - Sinta : -6 - Tahun : 2020",
    "Keyword : Industri - Nama Jurnal : Jurnal Intent :Jurnal Industri dan Teknologi Terpadu - Instansi : Universitas Banten Jaya - Website : http://ejournal.lppmunbaja.ac.id/index.php/intent - Waktu Terbit : Agustus - Biaya : - Sinta : 6 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : JTII (Jurnal Teknologi Informasi Indonesia) - Instansi : Prodi TI Politeknik Gorontalo - Website : http://jurnal.poligon.ac.id/index.php/JTII - Waktu Terbit : - Mei, November - Biaya : 350 - Sinta : 6 - Tahun : -2020",
    "Keyword : Teknologi - Nama Jurnal : Infotronik : Jurnal Teknologi Informasi dan Elektronika - Instansi : Universitas Sangga Buana - Website : http://jurnal.usbypkp.ac.id/index.php/infotronik - Waktu Terbit : - Juni, Desember - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Ilmiah Betrik : Besemah Teknologi Informasi dan Komputer - Instansi : Sekolah Tinggi Teknologi Pagar Alam - Website : https://ejournal.lppmsttpagaralam.ac.id/index.php/betrik - Waktu Terbit : - April, Oktober, Desember - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Komputer - Nama Jurnal : MATICS : Jurnal Ilmu Komputer dan Teknologi Informasi - Instansi : Jurusan Ilmu Komputer, Fakultas Sains dan Teknologi, UIN Maulana Malik Ibrahim - Website : http://ejournal.uinmalang.ac.id/index.php/saintek - Waktu Terbit : - Maret  September - Biaya : - Sinta : 5 - Tahun : 2018",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi - Instansi : Fakultas Teknologi Industri - IST AKPRIND Yogyakarta - Website : https://ejournal.akprind.ac.id/index.php/jurtek - Waktu Terbit : - Juni  Desember - Biaya : - Sinta : -5 - Tahun : 2021",
    "Keyword : Pengetahuan Teknologi - Nama Jurnal : SCIENCE TECH: Jurnal Ilmiah Ilmu Pengetahuan dan Teknologi - Instansi : Lembaga Penelitian, Pengembangan dan Pengabdian kepada Masyarakat (LP3M) Universitas Sarjanawiyata Tamansiswa (UST) Yogyakarta - Website : https://jurnal.ustjogja.ac.id/index.php/sciencetech - Waktu Terbit : - Februari Agustus - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Educate: Jurnal Teknologi Pendidikan - Instansi : Program Studi Teknologi Pendidikan FKIP Universitas Ibn Khaldun Bogor - Website : http://ejournal.uika-bogor.ac.id/index.php/EDUCATE q- Waktu Terbit : Januari, Juli - Biaya : 25,50 USD - Sinta : -4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Edutech: Jurnal Teknologi Pendidikan - Instansi : Prodi Teknologi Pendidikan Universitas Pendidikan Indonesia - Website : https://ejournal.upi.edu/index.php/edutech - Waktu Terbit : Februari, Juni, Oktober - Biaya : Penulis Indonesia: Rp 500.000 per artikel, Penulis internasional: 60 USD per artikel - Sinta : 4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : JKTP: Jurnal Kajian Teknologi Pendidikan - Instansi : Jurusan Teknologi Pendidikan Universitas Negeri Malang - Website : https://uia.e-journal.id/index.php/akademika/ - Waktu Terbit : Januari-Juni dan Juli-Desember - Biaya : 750 - Sinta : 4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Teknologi Pendidikan - Instansi : Prodi Teknologi Pendidikan Sekolah Pascasarjana Univ. Ibn Khaldun - Website : http://ejournal.uika-bogor.ac.id/index.php/TEK - Waktu Terbit : Januari, Juli - Biaya : 750 - Sinta : 4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Teknologi Pendidikan - Instansi : Program Studi Teknologi Pendidikan Program Pascasarjana Universitas Negeri Medan - Website : https://jurnal.unimed.ac.id/2012/index.php/jtp/index - Waktu Terbit : April, Oktober - Biaya : - Sinta : 4 - Tahun : 2021",
    "Keyword : Informatika - Nama Jurnal : Jurnal Informatika: Jurnal Pengembangan IT - Instansi : Pusat Penelitian dan Pengabdian Masyarakat (P3M) Politeknik Harapan Bersama - Website : http://ejournal.poltektegal.ac.id/index.php/informatika - Waktu Terbit : Januari, Mei, September - Biaya : 300 - Sinta : 3 - Tahun : 2020",
    "Keyword : Informatika - Nama Jurnal : JIKO (Jurnal Informatika dan Komputer) - Instansi : Prodi Teknik Informatika Fakultas Teknik Universitas Khairun - Website : http://ejournal.unkhair.ac.id/index.php/jiko - Waktu Terbit : April, Agustus, Desember - Biaya : 500 - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : Edcomtech: Jurnal Kajian Teknologi Pendidikan - Instansi : Program Studi Teknologi Pendidikan Universitas Negeri Malang - Website : http://journal2.um.ac.id/index.php/edcomtech/index - Waktu Terbit : April, Oktober - Biaya : 500.000 (sejak tahun 2022) dan 350.000 (tahun 2021) - Sinta : 3 - Tahun : -2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Inovasi Teknologi Pendidikan - Instansi : Program Pascasarjana Universitas Negeri Yogyakarta - Website : https://journal.uny.ac.id/index.php/jitp - Waktu Terbit : April, Oktober - Biaya : 500 - Sinta : 3 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Ilmiah Teknologi Informasi Asia - Instansi : STMIK Asia Malang - Website : https://jurnal.untan.ac.id/index.php/justin/index - Waktu Terbit : Februari, Agustus - Biaya : 150 - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : JUSTIN (Jurnal Sistem dan Teknologi Informasi) - Instansi : Program Studi Informatika Universitas Tanjungpura - Website : https://jurnal.untan.ac.id/index.php/justin/index - Waktu Terbit : January, April, July, October - Biaya : 200 - Sinta : 3 – Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : InfoTekJar : Jurnal Nasional Informatika dan Teknologi Jaringan - Instansi : Universitas Islam Sumatera Utara - Website : https://jurnal.uisu.ac.id/index.php/infotekjar - Waktu Terbit : - Maret, September - Biaya : 500 - Sinta : 3 - Tahun : 2021",
    "Keyword : -Pendidikan Teknologi - Nama Jurnal : -Jurnal Pendidikan Teknologi dan Kejuruan - Instansi : -Fakultas Teknik dan Kejuruan, Universitas Pendidikan Ganesha (Undiksha) - Website : https://ejournal.undiksha.ac.id/index.php/JPTK - Waktu Terbit : -Januari, Juli - Biaya : -Biaya Gratis - Sinta : -3 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -INVOTEK: Jurnal Inovasi Vokasional dan Teknologi - Instansi : -Fakultas Teknik Universitas Negeri Padang - Website : http://invotek.ppj.unp.ac.id/index.php/invotek - Waktu Terbit : - April, Oktober - Biaya : -500 - Sinta : 3 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : -Lontar Komputer : Jurnal Ilmiah Teknologi Informasi - Instansi : -Research Institutions and Community Service, Udayana University, Bali-Indonesia - Website : https://ojs.unud.ac.id/index.php/lontar - Waktu Terbit : -Marer, April - Biaya : - Sinta : -2 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -Jurnal Teknologi Informasi dan Komunikasi - Instansi : -LPPM STIMIK Pro Visi Semarang - Website : http://ejurnal.provisi.ac.id/index.php/JTIKP - Waktu Terbit : - April, September - Biaya : -100.000/ eksemplar ditambah Rp.25.000 jika ada ongkos kirim - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -Infotek : Jurnal Informatika dan Teknologi - Instansi : -Universitas Hamzanwadi - Website : https://ejournal.hamzanwadi.ac.id/index.php/infotek - Waktu Terbit : -Januari, Juli - Biaya : 200 - Sinta : -5 - Tahun : -2021",
    "Keyword : Teknologi - Nama Jurnal : -Informasi Interaktif : Jurnal Informatika dan Teknologi Informasi - Instansi : -Program Studi Teknik Informatika Fakultas Teknik Universitas Janabadra - Website : http://ejournal.janabadra.ac.id/index.php/informasiinteraktif - Waktu Terbit : -Januari, Mei, September - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -JUST IT : Jurnal Sistem Informasi, Teknologi Informasi dan Komputer - Instansi : -Program Teknik Informatika, Fakultas Teknik Universitas Muhammadiyah Jakarta - Website : https://jurnal.umj.ac.id/index.php/just-it - Waktu Terbit : - Septembee, Januari, Mei - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -JTPII (Jurnal Teknologi Proses dan Inovasi Industri) - Instansi : -Balai Riset dan Standardisasi (Baristand) Industri Surabaya - Website : http://ejournal.kemenperin.go.id/jtpii - Waktu Terbit : - Juli, Desember - Biaya : Gratis - Sinta : 5 – Tahun : 2020",
    "Keyword : -Teknologi - Nama Jurnal : -Praxis : Jurnal Sains, Teknologi, Masyarakat dan Jejaring - Instansi : -Universitas Katolik Soegijapranata - Website : http://journal.unika.ac.id/index.php/praxis - Waktu Terbit : - September, Maret - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : -TEKNOLOGI: Jurnal Ilmiah Sistem Informasi - Instansi : -Prodi Sistem Informasi Fakultas Teknik Universitas Pesantren Tinggi Darul Ulum (Unipdu) Jombang - Website : http://www.journal.unipdu.ac.id/index.php/teknologi - Waktu Terbit : -Januari, Juli - Biaya : -150 - Sinta : 5 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : -Smart Comp :Jurnalnya Orang Pintar Komputer - Instansi : -Pusat Penelitian Dan Pengabdian kepada Masyarakat (P3M) Politeknik Harapan Bersama - Website : https://ejournal.poltektegal.ac.id/index.php/smartcomp - Waktu Terbit : -Januari, Juni - Biaya : -250 - Sinta : 5 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : -Jurnal Teknovasi : Jurnal Teknik dan Inovasi Mesin Otomotif, Komputer, Industri dan Elektronika - Instansi : -LPPM Politeknik LP3I Medan - Website : https://ejurnal.plm.ac.id/index.php/teknovasi/index - Waktu Terbit : -April, Oktober - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : -Jurnal Teknik Elektro dan Komputer - Instansi : -Prodi Teknik Elektro, Universitas Sam Ratulangi Manado - Website : https://ejournal.unsrat.ac.id/index.php/elekdankom - Waktu Terbit : -April, Agustus, Desember - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : -Jurnal Ilmu Komputer dan Bisnis - Instansi : -Sekolah Tinggi Manajemen Informatika Dan Komputer Dharmapala Riau - Website : https://stmikdharmapalariau.ac.id/ojs/index.php/jikb - Waktu Terbit : -Mei, November - Biaya : -200 - Sinta : 6 - Tahun : 2020",
    "Keyword : Komputer - Nama Jurnal : -Jurnal Ilmiah Komputer Grafis - Instansi : - Website : http://jurnal.stekom.ac.id/index.php/pixel - Waktu Terbit : -Juli, Desember - Biaya : Gratis - Sinta : 6 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Jurnal Ilmu Komputer dan Bisnis (JIKB) - Instansi : STMIK Dharmapala Riau - Website : https://stmikdharmapalariau.ac.id/ojs/index.php/jikb - Waktu Terbit : Mei, November - Biaya : 200,000 - Sinta : 1 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Teknologi Pendidikan - Instansi : Universitas Negeri Jakarta - Website : http://journal.unj.ac.id/unj/index.php/jtp/about - Waktu Terbit : April, Agustus, Desember - Biaya : 1,200,000 - Sinta : 2 - Tahun : 1999",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Education Technology - Instansi : Universitas Pendidikan Indonesia - Website : https://ejournal.upi.edu/index.php/edutech - Waktu Terbit : Februari,Juni, Oktober - Biaya : 500,000 - Sinta : 4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Inovasi Teknologi Pendidikan - Instansi : Universitas Negeri Yogyakarta - Website : https://journal.uny.ac.id/index.php/jitp/index - Waktu Terbit : April, Oktober - Biaya : 500,000 - Sinta : 3 - Tahun : 2014",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Kajian Teknologi Pendidikan - Instansi : Universitas Negeri Malang - Website : http://journal2.um.ac.id/index.php/edcomtech/ - Waktu Terbit : Juli, April, Februari - Biaya : 350,000 - Sinta : 3 - Tahun : 2018",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Lentera: Kajian Keagamaan, Keilmuan dan Teknologi - Instansi : Sekolah Tinggi Agama Islam Miftahul Ula Nganjuk - Website : https://www.neliti.com/journals/jurnal-lentera-kajiankeagamaan-keilmuan-dan-teknologi/catalogue - Waktu Terbit : maret, september - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : Jurnal Teknologi Komunikasi dan Informasi - Instansi : Politeknik Gorontalo - Website : http://jurnal.poligon.ac.id/index.php/JTII/about - Waktu Terbit : Mei, November - Biaya : - Sinta : 6 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : JKTP: Jurnal Kajian Teknologi Pendidikan - Instansi : Jurusan Teknologi Pendidikan Universitas Negeri Malang - Website : https://uia.e-journal.id/index.php/akademika/ - Waktu Terbit : Januari-Juni dan Juli-Desember - Biaya : 750 - Sinta : 4 - Tahun : 2021",
    "Keyword : Teknologi Pendidikan - Nama Jurnal : MATICS : Jurnal Ilmu Komputer dan Teknologi Informasi - Instansi : Jurusan Ilmu Komputer, Fakultas Sains dan Teknologi, UIN Maulana Malik Ibrahim - Website : http://ejournal.uinmalang.ac.id/index.php/saintek - Waktu Terbit : maret, september - Biaya : - Sinta : 5 - Tahun : 2018",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Informasi dan Komputer - Instansi : Unversitas Dhyana Putra - Website : http://jurnal.undhirabali.ac.id/index.php/jutik/index - Waktu Terbit : juni - Biaya : - Sinta : 6 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : JURNAL TEKNOLOGI TECHNOSCIENTIA - Instansi : Institut Sains & Teknologi AKPRIND Yogyakarta - Website : https://ejournal.akprind.ac.id/index.php/technoscientia/about - Waktu Terbit : Februari, Agustus - Biaya : 250,000 - Sinta : 6 - Tahun : 2018",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Informasi - Instansi : Universitas Respati Indonesia - Website : http://ejournal.urindo.ac.id/index.php/TI - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 6 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : METHOMIKA: Jurnal Manajemen Informatika dan Komputerisasi Akuntansi - Instansi : Universitas Methodist Indonesia - Website : http://methomika.net/index.php/jmika - Waktu Terbit : April - Biaya : - Sinta : 6 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Jurnal Ilmiah Teknik Elektro Komputer dan Informatika (JITEKI) - Instansi : Universitas Ahmad Dahlan - Website : http://journal.uad.ac.id/index.php/JITEKI/ - Waktu Terbit : April, Agustus, dan December - Biaya : - Sinta : 2 - Tahun : 2019","Keyword : Komputer - Nama Jurnal : Jurnal Teknik Informasi dan Komputer (Tekinkom) - Instansi : Politeknik Bisnis Indonesia - Website : http://jurnal.murnisadar.ac.id/index.php/Tekinkom - Waktu Terbit : Desember - Biaya : - Sinta : 4 - Tahun : 2020",
    "Keyword : Komputer - Nama Jurnal : Jurnal CoreIT: Jurnal Hasil Penelitian Ilmu Komputer dan Teknologi Informasi - Instansi : Program Studi Teknik Informatika - Universitas Islam Negeri Sultan Syarif Kasim Riau - Website : http://ejournal.uin-suska.ac.id/index.php/coreit - Waktu Terbit : Juni dan December - Biaya : - Sinta : 4 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Jusikom : Jurnal Sistem Komputer Musirawas - Instansi : LPPM Universitas Bina Insan Lubuklinggau - Website : http://jurnal.univbinainsan.ac.id/index.php/jusikom - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 4 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Matics: Jurnal Ilmu Komputer dan Teknologi Informasi (Journal of Computer Science and Information Technology) - Instansi : Teknik Informatika Universitas Islam Negeri Maulana Malik Ibrahim Malang - Website : http://ejournal.uin-malang.ac.id/index.php/saintek - Waktu Terbit : Maret, September - Biaya : - Sinta : 4 - Tahun : 2019",
    "Keyword : Komputer - Nama Jurnal : Bianglala Informatika : Jurnal Komputer dan Informatika Akademi Bina Sarana Informatika Yogyakarta - Instansi : Universitas Bina Sarana Informatika - Website : https://ejournal.bsi.ac.id/ejurnal/index.php/Bianglala/ - Waktu Terbit : Maret dan September. - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Komputer - Nama Jurnal : Pixel : Jurnal Ilmiah Komputer Grafis - Instansi : Sekolah Tinggi Elektronik dan Komputer Pat - Website : http://jurnal.stekom.ac.id/index.php/pixel - Waktu Terbit : Juli dan Desember - Biaya : - Sinta : 6 - Tahun : 2016",
    "Keyword : Komputer - Nama Jurnal : Jurnal Ilmiah Ilmu Komputer Fakultas Ilmu Komputer Universitas Al Asyariah Mandar - Instansi : Lembaga Penelitian dan Pengabdian Masyarakat, Universitas Al Asyariah Mandar - Website : http://ejournal.fikom-unasman.ac.id/index.php/jikom - Waktu Terbit : April dan September - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : JURNAL TIKA Fakultas Ilmu Komputer Universitas Al Muslim - Instansi : Universitas Al Muslim - Website : http://jurnal.umuslim.ac.id/index.php/tika - Waktu Terbit : Agustus - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Komputer - Nama Jurnal : Jurnal Teknologi Informasi dan Ilmu Komputer - Instansi : Fakultas Ilmu Komputer Universitas Brawijaya - Website : https://jtiik.ub.ac.id/index.php/jtiik - Waktu Terbit : Januari - Biaya : 300,000 - Sinta : 2 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Jurnal Komputer Terapan - Instansi : Politeknik Caltex Riau - Website : https://jurnal.pcr.ac.id/index.php/jkt/index - Waktu Terbit : Juni - Biaya : - Sinta : 3 - Tahun : 2021",
    "Keyword : Komputer - Nama Jurnal : Jurnal CoreIT: Jurnal Hasil Penelitian Ilmu Komputer dan Teknologi Informasi - Instansi : Program Studi Teknik Informatika - Universitas Islam Negeri Sultan Syarif Kasim Riau - Website : http://ejournal.uin-suska.ac.id/index.php/coreit - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 4 - Tahun : 2015",
    "Keyword : Teknologi - Nama Jurnal : Jurnal RESTI (Rekayasa Sistem dan Teknologi Informasi) - Instansi : Ikatan Ahli Informatika Indonesia (IAII) - Website : http://jurnal.iaii.or.id/index.php/RESTI - Waktu Terbit : Desember - Biaya : - Sinta : 2 - Tahun : 2019",
    "Keyword : Teknologi - Nama Jurnal : Jurnal IPTEK-KOM (Jurnal Ilmu Pengetahuan dan Teknologi Komunikasi) - Instansi : Balai Pengkajian dan Pengembangan Komunikasi dan Informatika Yogyakarta - Website : https://jurnal.kominfo.go.id/index.php/iptekkom - Waktu Terbit : Juni - Biaya : - Sinta : 2 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : InfoTekJar : Jurnal Nasional Informatika dan Teknologi Jaringan - Instansi : Universitas Islam Sumatera Utara - Website : https://jurnal.uisu.ac.id/index.php/infotekjar - Waktu Terbit : Maret dan September - Biaya : - Sinta : 3 - Tahun : 2016",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Informasi dan Pendidikan - Instansi : Universitas Negeri Padang - Website : http://tip.ppj.unp.ac.id/index.php/tip - Waktu Terbit : Maret - Biaya : - Sinta : 3 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : JURTEKSI (Jurnal Teknologi dan Sistem Informasi) - Instansi : Lembaga Penelitian dan Pengabdian Kepada Masyarakat (LPPM) STMIK ROYAL Kisaran - Website : https://jurnal.stmikroyal.ac.id/index.php/jurteksi - Waktu Terbit : Juni - Biaya : - Sinta : 3 - Tahun : 2018",
    "Keyword : Teknologi - Nama Jurnal : Digital Zone: Jurnal Teknologi Informasi dan Komunikasi - Instansi : Universitas Lancang Kuning- Website : https://journal.unilak.ac.id/index.php/dz/index - Waktu Terbit : April - Biaya : - Sinta : 3 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : (JTERA) Jurnal Teknologi Rekayasa - Instansi : Politeknik Sukabumi - Website : https://jtera.polteksmi.ac.id/index.php/jtera - Waktu Terbit : Oktober, April - Biaya : - Sinta : 3 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : Techno.Com: Jurnal Teknologi Informasi - Instansi : LPPM Universitas Dian Nuswantoro - Website : http://publikasi.dinus.ac.id/index.php/technoc/index - Waktu Terbit : April - Biaya : - Sinta : 3 - Tahun : 2016",
    "Keyword : Teknologi - Nama Jurnal : MATRIX - Jurnal Manajemen Teknologi dan Informatika - Instansi : Politeknik Negeri Bali - Website : http://ojs.pnb.ac.id/index.php/matrix - Waktu Terbit : Maret, Juli, November - Biaya : - Sinta : 3 - Tahun : 2018",
    "Keyword : Informasi - Nama Jurnal : JurTI (Journal of Information Technology) - Instansi : journal is published by Asahan University - Website : http://jurnal.una.ac.id/index.php/jurti - Waktu Terbit : Juni dan December - Biaya : - Sinta : 5 - Tahun : 2019",
    "Keyword : Teknologi - Nama Jurnal : JURTEKSI (Jurnal Teknologi dan Sistem Informasi) - Instansi : Lembaga Penelitian dan Pengabdian Kepada Masyarakat (LPPM) STMIK ROYAL Kisaran - Website : https://jurnal.stmikroyal.ac.id/index.php/jurteksi - Waktu Terbit : Juni - Biaya : - Sinta : 3 - Tahun : 2018",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Informasi dan Komunikasi (PETIK) - Instansi : Prodi Pendidikan Teknologi Informasi Institut Pendidikan Indonesia Garut - Website : https://journal.institutpendidikan.ac.id/index.php/petik - Waktu Terbit : Maret dan September - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Informasi - Nama Jurnal : Jurnal Sistem Informasi dan Telematika (Telekomunikasi, Multimedia dan Informatika) - Instansi : Teknologi Informasi - Fakultas IlmuKomputer Universitas Bandar Lampung - Website : http://jurnal.ubl.ac.id/index.php/explore - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 5 - Tahun : 2020",
    "Keyword : Pendidikan teknik - Nama Jurnal : Jurnal Pendidikan Teknik Elektro Undiksha - Instansi : Program Studi Pendidikan Teknik Elektro, Jurusan Teknologi Industri, Fakultas Teknik dan Kejuruan, Universitas Pendidikan Ganesha - Website : https://ejournal.undiksha.ac.id/index.php/JJPTE - Waktu Terbit : April, August, December - Biaya : - Sinta : 5 - Tahun : 2019",
    "Keyword : Informatika - Nama Jurnal : (Jurnal Manajemen Informatika dan Sistem Informasi) - Instansi : LPPM STMIK Lombok - Website : http://ejournal.stmiklombok.ac.id/index.php/misi - Waktu Terbit : Januari dan Juni - Biaya : - Sinta : 5 - Tahun : 2021",
    "Keyword : Teknologi Informasi - Nama Jurnal : Jurnal Teknologi Informasi dan Ilmu Komputer - Instansi : Fakultas Ilmu Komputer Universitas Brawijaya - Website : https://jtiik.ub.ac.id/index.php/jtiik - Waktu Terbit : April dan Oktober - Biaya : 300,000 - Sinta : 2 - Tahun : 2014",
    "Keyword : Teknologi Informasi - Nama Jurnal : Jurnal RESTI (Rekayasa Sistem dan Teknologi Informasi) - Instansi : Ikatan Ahli Informatika Indonesia (IAII) - Website : http://jurnal.iaii.or.id/index.php/RESTI - Waktu Terbit : Februari, April, Juni, Agustus, Oktober dan Desember - Biaya : - Sinta : 2 - Tahun : 2017",
    "Keyword : Teknologi Informasi - Nama Jurnal : Jurnal Teknologi Informasi dan Pendidikan - Instansi : Universitas Negeri Padang - Website : http://tip.ppj.unp.ac.id/index.php/tip - Waktu Terbit : Maret dan September - Biaya : 500,000 - Sinta : 3 - Tahun : 2014",
    "Keyword : Teknologi Informasi - Nama Jurnal : Digital Zone: Jurnal Teknologi Informasi dan Komunikasi - Instansi : Fakultas Ilmu Komputer-Universitas Lancang Kuning - Website : https://journal.unilak.ac.id/index.php/dz/about - Waktu Terbit : Mei dan November - Biaya : 500,000 - Sinta : 3 - Tahun : 2017",
    "Keyword : Teknologi Informasi - Nama Jurnal : JUTI: Jurnal Ilmiah Teknologi Informasi - Instansi : Institut Teknologi Sepuluh Nopember - Website : http://juti.if.its.ac.id/index.php/juti/index - Waktu Terbit : Januari dan Juli - Biaya : - Sinta : 3 - Tahun : 2016",
    "Keyword : Teknologi Informasi - Nama Jurnal : Telematika : Jurnal Informatika dan Teknologi Informasi - Instansi : Universitas Pembangunan Nasional Veteran Yogyakarta - Website : http://jurnal.upnyk.ac.id/index.php/telematika/index - Waktu Terbit : Februari, Juni, dan Oktober - Biaya : - Sinta : 3 - Tahun : 2015",
    "Keyword : Teknologi Informasi - Nama Jurnal : Jurnal Ilmiah Merpati (Menara Penelitian Akademika Teknologi Informasi) - Instansi : Program Studi Teknologi Informasi Universitas Udayana - Website : https://ojs.unud.ac.id/index.php/merpati/ - Waktu Terbit : April, Agustus, dan Desember - Biaya : - Sinta : 3 - Tahun : 2013",
    "Keyword : Teknologi Informasi - Nama Jurnal : Cyberspace: Jurnal Pendidikan Teknologi Informasi - Instansi : Universitas Islam Negeri Ar-Raniry Banda Aceh - Website : http://jurnal.ar-raniry.ac.id/index.php/cyberspace - Waktu Terbit : Maret dan Oktober - Biaya : - Sinta : 3 - Tahun : 2017",
    "Keyword : Teknologi Informasi - Nama Jurnal : Jurnal CoreIT: Jurnal Hasil Penelitian Ilmu Komputer dan Teknologi Informasi - Instansi : Program Studi Teknik Informatika - Universitas Islam Negeri Sultan Syarif Kasim Riau - Website : http://ejournal.uin-suska.ac.id/index.php/coreit - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 3 - Tahun : 2015",
    "Keyword : Teknologi Informasi - Nama Jurnal : JurTI (Jurnal Teknologi Informasi) - Instansi : Prodi Teknik Informatika FT Universitas Asahan - Website : http://jurnal.una.ac.id/index.php/jurti - Waktu Terbit : Juni dan Desember - Biaya : 200,000 - Sinta : 5 - Tahun : 2017",
    "Keyword : Teknologi - Nama Jurnal : Jurnal IPTEK-KOM (Jurnal Ilmu Pengetahuan dan Teknologi Komunikasi) - Instansi : Balai Pengkajian dan Pengembangan Komunikasi dan Informatika Yogyakarta - Website : https://jurnal.kominfo.go.id/index.php/iptekkom - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 2 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Pendidikan Teknologi dan Kejuruan - Instansi : Universitas Negeri Yogyakarta - Website : https://journal.uny.ac.id/index.php/jptk - Waktu Terbit : Mei dan Oktober - Biaya : - Sinta : 2 - Tahun : 2017",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Sistem dan Teknologi Informasi - Instansi : Universitas Tanjungpura - Website : https://jurnal.untan.ac.id/index.php/justin/index - Waktu Terbit : January, April, July, October - Biaya : - Sinta : 3 - Tahun : 2019",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi - Instansi : Fakultas Teknik Universitas Muhammadiyah Jakarta - Website : https://jurnal.umj.ac.id/index.php/jurtek - Waktu Terbit : April - Biaya : - Sinta : 3 - Tahun : 2019",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Teknologi Rekayasa - Instansi : Politeknik Sukabumi - Website : https://jtera.polteksmi.ac.id/index.php/jtera - Waktu Terbit : Juni dan Desember - Biaya : - Sinta : 3 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Sains, Teknologi, Sosial, Pendidikan, dan Bahasa - Instansi : Universitas Negeri Jakarta - Website : https://ejurnal.kpmunj.org/index.php/risenologi - Waktu Terbit : Juni - Biaya : - Sinta : 3 - Tahun : 2020",
    "Keyword : Teknologi - Nama Jurnal : InfoTekJar : Jurnal Nasional Informatika dan Teknologi Jaringan - Instansi : Universitas Islam Sumatera Utara - Website : https://jurnal.uisu.ac.id/index.php/infotekjar - Waktu Terbit : Maret, September - Biaya : 500 - Sinta : 3 - Tahun : 2021",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Ilmiah Teknologi Informasi Asia - Instansi : STMIK Asia Malang - Website : https://jurnal.stmikasia.ac.id/index.php/jitika - Waktu Terbit : Mei - Biaya : - Sinta : 5 - Tahun : 2017",
    "Keyword : Teknologi - Nama Jurnal : Jurnal Ilmu Pengetahuan, Teknologi, dan Seni bagi Masyarakat - Instansi : Universitas Sebelas Maret Surakarta - Website : https://jurnal.uns.ac.id/jurnal-semar - Waktu Terbit : Mei, November - Biaya : - Sinta : 5 - Tahun : 2020",
    

];

function tampil() {
    var tabel = document.getElementById("tabel");
    tabel.innerHTML = "<tr><th>No</th><th>Nama</th><th>Action</th></tr>";
    for (let i = 0; i < data.length; i++) {
        var btnEdit = "<button class='btn btn-warning' href='#' onclick='edit(" + i + ")'>Edit</button>";
        var btnHapus = "<button class='btn btn-danger' href='#' onclick='hapus(" + i + ")'>Hapus</button>";
        j = i + 1;
        tabel.innerHTML += "<tr><td>" + j + "</td><td>" + data[i] + "</td><td>" + btnEdit + " " + btnHapus + "</tr>";
    }
}

function tambah() {
    var input = document.querySelector("input[name=jurusan]");
    data.push(input.value);
    tampil();
    input.value = "";
}

function edit(id) {
    var baru = prompt("Edit", data[id]);
    data[id] = baru;
    tampil();
}

function hapus(id) {
    data.pop(id);
    tampil();
}

tampil();
